config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  get '/articles/', to: 'articles#index'
  get '/articles/new', to: 'articles#new', as: :create
  get '/articles/:id', to: 'articles#show', as: :article
  post '/articles', to: 'articles#create'
  get '/articles/:id/edit', to: 'articles#edit', as: :edit
  patch '/articles/:id', to: 'articles#update'
  delete 'articles/:id', to: 'articles#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save!
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update!(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require('article').permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="container">
  <%= simple_form_for(@article) do |f| %>
    <%= f.input :title %>
    <%= f.input :content %>
    <input class="btn btn-primary" type="submit" value="Submit">
    <button class="btn btn-primary link-to"><%= link_to "Back to list", articles_path %></button>
  <% end %>
</div>

app/views/articles/index.html.erb
<div class="container index">
  <button class="btn btn-warning"><%= link_to "Create a new article", create_path %></button>

  <% @articles.each do |article| %>
    <h1><%= link_to article.title, article_path(article) %></h1>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="container">
  <%= simple_form_for(@article) do |f| %>
    <%= f.input :title %>
    <%= f.input :content %>
    <input class="btn btn-primary" type="submit" value="Submit">
    <button class="btn btn-primary link-to"><%= link_to "Back to list", root_path %></button>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="container article">
  <h1><%= @article.title %></h1>
  <p class="lead"><%= @article.content %></p>

  <button class="btn btn-success" type="submit"><%= link_to "Update the article",  edit_path(@article)%></button>
  <button class="btn btn-warning" type="submit"><%= link_to "Back to the list",  root_path%></button>
  <button class="btn btn-danger" type="submit"><%= link_to "Delete #{@article.title}", article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>